version: "3.9"

services:

  postgres:
    build: ./dockerfiles/postgres
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    ports:
      - "6432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf #wal_level = logical
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
