## Database
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:6432/postgres?currentSchema=public}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    # default connection pool
    hikari:
      connectionTimeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
      maximumPoolSize: ${HIKARI_MAX_POOL_SIZE:20}
  # JPA
#  jpa:
#    database-platform: ${JPA_DB_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
#    properties.hibernate:
#      temp.use_jdbc_metadata_defaults: false
#      default_schema: ${JPA_DEFAULT_SCHEMA}
#    hibernate.ddl-auto: validate

## logs
logging:
  #  pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    ru:
      gpb: ${LOGGING_LEVEL_RU_GPB:INFO}
#    .: error

## Metadata
